package frc.robot.util;

import edu.wpi.first.math.geometry.Pose3d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;

// Generated by shot_solver. Do not edit.
/**
 * Generated shot solver: distance tables + moving-shot solve.
 *
 * <p><b>Flywheel RPS conversion (William V5)</b>
 * <pre>
 *   WHEEL_RADIUS = mean(r_bottom, r_top)   // dual flywheel, same RPM
 *                 bottom 4in OD, top 2in OD
 *   EFF_RADIUS   = WHEEL_RADIUS * SLIP_FACTOR
 *   rps          = v_exit / (2 * pi * EFF_RADIUS)
 *   v_exit       = rps * 2 * pi * EFF_RADIUS
 * </pre>
 *
 * <p>Tables are {@link InterpolatingDoubleTreeMap} over distance
 * [0.50, 6.50] m (stationary optimum). {@code solve(...)} applies
 * turret/hood/flywheel remapping for robot motion.
 */
public final class ShotSolver {
  public static final double MIN_DISTANCE_M = 0.5;
  public static final double MAX_DISTANCE_M = 6.5;
  private static final double HOOD_MIN = 0.64606852921074098;
  private static final double HOOD_MAX = 1.2168959143680065;
  private static final double TURRET_MIN = -3.1415926535897931;
  private static final double TURRET_MAX = 3.1415926535897931;
  private static final double EXIT_SPEED_MIN = 2;
  private static final double EXIT_SPEED_MAX = 30;

  // Dual flywheel mean radius: bottom 4in OD + top 2in OD.
  private static final double WHEEL_RADIUS = 0.038099999999999995;
  private static final double SLIP_FACTOR = 0.75;
  // EFF_RADIUS = WHEEL_RADIUS * SLIP_FACTOR
  private static final double EFF_RADIUS = WHEEL_RADIUS * SLIP_FACTOR;
  private static final Translation3d LAUNCHER_OFFSET =
      new Translation3d(0.15925607, 0, 0.47184857000000002);
  private static final Translation3d TURRET_PIVOT =
      new Translation3d(0.15925607, 0, 0);
  private static final double BALL_DWELL_TIME = 0.20000000000000001;

  private static final InterpolatingDoubleTreeMap HOOD_ANGLE_MAP =
      new InterpolatingDoubleTreeMap();
  private static final InterpolatingDoubleTreeMap FLYWHEEL_SPEED_MAP =
      new InterpolatingDoubleTreeMap();
  private static final InterpolatingDoubleTreeMap TIME_OF_FLIGHT_MAP =
      new InterpolatingDoubleTreeMap();

  static {
    // Hood [rad], flywheel [rot/s], ToF [s] vs distance [m]
    // rps = v_exit / (2*pi*EFF_RADIUS)
    HOOD_ANGLE_MAP.put(0.50, 1.208937); // 69.3 deg
    FLYWHEEL_SPEED_MAP.put(0.50, 31.34); // v=5.63 m/s
    TIME_OF_FLIGHT_MAP.put(0.50, 0.584446);
    HOOD_ANGLE_MAP.put(0.75, 1.195847); // 68.5 deg
    FLYWHEEL_SPEED_MAP.put(0.75, 32.22); // v=5.78 m/s
    TIME_OF_FLIGHT_MAP.put(0.75, 0.665428);
    HOOD_ANGLE_MAP.put(1.00, 1.204574); // 69.0 deg
    FLYWHEEL_SPEED_MAP.put(1.00, 31.84); // v=5.72 m/s
    TIME_OF_FLIGHT_MAP.put(1.00, 0.642767);
    HOOD_ANGLE_MAP.put(1.25, 1.165304); // 66.8 deg
    FLYWHEEL_SPEED_MAP.put(1.25, 32.56); // v=5.85 m/s
    TIME_OF_FLIGHT_MAP.put(1.25, 0.662821);
    HOOD_ANGLE_MAP.put(1.50, 1.191484); // 68.3 deg
    FLYWHEEL_SPEED_MAP.put(1.50, 34.20); // v=6.14 m/s
    TIME_OF_FLIGHT_MAP.put(1.50, 0.798614);
    HOOD_ANGLE_MAP.put(1.75, 1.174031); // 67.3 deg
    FLYWHEEL_SPEED_MAP.put(1.75, 34.61); // v=6.21 m/s
    TIME_OF_FLIGHT_MAP.put(1.75, 0.808411);
    HOOD_ANGLE_MAP.put(2.00, 1.169667); // 67.0 deg
    FLYWHEEL_SPEED_MAP.put(2.00, 35.53); // v=6.38 m/s
    TIME_OF_FLIGHT_MAP.put(2.00, 0.855332);
    HOOD_ANGLE_MAP.put(2.25, 1.169667); // 67.0 deg
    FLYWHEEL_SPEED_MAP.put(2.25, 36.95); // v=6.63 m/s
    TIME_OF_FLIGHT_MAP.put(2.25, 0.925910);
    HOOD_ANGLE_MAP.put(2.50, 1.169667); // 67.0 deg
    FLYWHEEL_SPEED_MAP.put(2.50, 38.71); // v=6.95 m/s
    TIME_OF_FLIGHT_MAP.put(2.50, 1.006713);
    HOOD_ANGLE_MAP.put(2.75, 1.169667); // 67.0 deg
    FLYWHEEL_SPEED_MAP.put(2.75, 40.25); // v=7.23 m/s
    TIME_OF_FLIGHT_MAP.put(2.75, 1.072984);
    HOOD_ANGLE_MAP.put(3.00, 1.169667); // 67.0 deg
    FLYWHEEL_SPEED_MAP.put(3.00, 41.78); // v=7.50 m/s
    TIME_OF_FLIGHT_MAP.put(3.00, 1.136790);
    HOOD_ANGLE_MAP.put(3.25, 1.160941); // 66.5 deg
    FLYWHEEL_SPEED_MAP.put(3.25, 42.99); // v=7.72 m/s
    TIME_OF_FLIGHT_MAP.put(3.25, 1.179528);
    HOOD_ANGLE_MAP.put(3.50, 1.134761); // 65.0 deg
    FLYWHEEL_SPEED_MAP.put(3.50, 43.54); // v=7.82 m/s
    TIME_OF_FLIGHT_MAP.put(3.50, 1.183075);
    HOOD_ANGLE_MAP.put(3.75, 1.117307); // 64.0 deg
    FLYWHEEL_SPEED_MAP.put(3.75, 44.37); // v=7.97 m/s
    TIME_OF_FLIGHT_MAP.put(3.75, 1.202295);
    HOOD_ANGLE_MAP.put(4.00, 1.095491); // 62.8 deg
    FLYWHEEL_SPEED_MAP.put(4.00, 45.04); // v=8.09 m/s
    TIME_OF_FLIGHT_MAP.put(4.00, 1.210995);
    HOOD_ANGLE_MAP.put(4.25, 1.099854); // 63.0 deg
    FLYWHEEL_SPEED_MAP.put(4.25, 46.47); // v=8.34 m/s
    TIME_OF_FLIGHT_MAP.put(4.25, 1.268804);
    HOOD_ANGLE_MAP.put(4.50, 1.073674); // 61.5 deg
    FLYWHEEL_SPEED_MAP.put(4.50, 46.94); // v=8.43 m/s
    TIME_OF_FLIGHT_MAP.put(4.50, 1.264693);
    HOOD_ANGLE_MAP.put(4.75, 1.051858); // 60.3 deg
    FLYWHEEL_SPEED_MAP.put(4.75, 47.55); // v=8.54 m/s
    TIME_OF_FLIGHT_MAP.put(4.75, 1.268249);
    HOOD_ANGLE_MAP.put(5.00, 1.051858); // 60.3 deg
    FLYWHEEL_SPEED_MAP.put(5.00, 48.73); // v=8.75 m/s
    TIME_OF_FLIGHT_MAP.put(5.00, 1.311454);
    HOOD_ANGLE_MAP.put(5.25, 1.043131); // 59.8 deg
    FLYWHEEL_SPEED_MAP.put(5.25, 49.65); // v=8.91 m/s
    TIME_OF_FLIGHT_MAP.put(5.25, 1.336822);
    HOOD_ANGLE_MAP.put(5.50, 1.021314); // 58.5 deg
    FLYWHEEL_SPEED_MAP.put(5.50, 50.21); // v=9.02 m/s
    TIME_OF_FLIGHT_MAP.put(5.50, 1.336013);
    HOOD_ANGLE_MAP.put(5.75, 1.030041); // 59.0 deg
    FLYWHEEL_SPEED_MAP.put(5.75, 51.56); // v=9.26 m/s
    TIME_OF_FLIGHT_MAP.put(5.75, 1.392248);
    HOOD_ANGLE_MAP.put(6.00, 0.986408); // 56.5 deg
    FLYWHEEL_SPEED_MAP.put(6.00, 51.57); // v=9.26 m/s
    TIME_OF_FLIGHT_MAP.put(6.00, 1.348140);
    HOOD_ANGLE_MAP.put(6.25, 1.003861); // 57.5 deg
    FLYWHEEL_SPEED_MAP.put(6.25, 53.04); // v=9.52 m/s
    TIME_OF_FLIGHT_MAP.put(6.25, 1.417707);
    HOOD_ANGLE_MAP.put(6.50, 0.995134); // 57.0 deg
    FLYWHEEL_SPEED_MAP.put(6.50, 53.87); // v=9.67 m/s
    TIME_OF_FLIGHT_MAP.put(6.50, 1.437383);
  }

  public record Calibration(double hoodBiasRad, double mpsScale) {
    public static Calibration identity() {
      return new Calibration(0.0, 1.0);
    }
  }

  public record Solution(
      boolean valid,
      double turretYawRad,
      double hoodRad,
      double flywheelRps,
      double tofSec,
      double exitSpeedMps,
      double radialVelocityMps,
      double tangentialVelocityMps,
      double robustnessSigma,
      double angleToleranceDownRad,
      double angleToleranceUpRad,
      double speedToleranceDownMps,
      double speedToleranceUpMps) {}

  private ShotSolver() {}

  public static double hoodAngleRad(double distanceMeters) {
    distanceMeters =
        Math.max(MIN_DISTANCE_M, Math.min(distanceMeters, MAX_DISTANCE_M));
    return HOOD_ANGLE_MAP.get(distanceMeters);
  }

  /** Table flywheel command [rot/s]. */
  public static double flywheelSpeedRotPerSec(double distanceMeters) {
    distanceMeters =
        Math.max(MIN_DISTANCE_M, Math.min(distanceMeters, MAX_DISTANCE_M));
    return FLYWHEEL_SPEED_MAP.get(distanceMeters);
  }

  /** Ball exit speed [m/s] from table RPS: v = rps * 2*pi * EFF_RADIUS. */
  public static double exitSpeedMps(double distanceMeters) {
    return flywheelSpeedRotPerSec(distanceMeters) *
        2.0 * Math.PI * EFF_RADIUS;
  }

  public static double timeOfFlightS(double distanceMeters) {
    distanceMeters =
        Math.max(MIN_DISTANCE_M, Math.min(distanceMeters, MAX_DISTANCE_M));
    return TIME_OF_FLIGHT_MAP.get(distanceMeters);
  }

  public static Solution solve(
      Pose3d robotPose,
      Translation2d fieldVelocityMps,
      double yawRateRadPerSec,
      Translation3d hubCenter,
      Calibration calibration) {
    return solve(
        robotPose,
        fieldVelocityMps,
        yawRateRadPerSec,
        0.0,
        hubCenter,
        calibration);
  }

  public static Solution solve(
      Pose3d robotPose,
      Translation2d fieldVelocityMps,
      double yawRateRadPerSec,
      double turretYawRateRadPerSec,
      Translation3d hubCenter,
      Calibration calibration) {
    return solve(
        robotPose,
        fieldVelocityMps,
        new Translation3d(0.0, 0.0, yawRateRadPerSec),
        turretYawRateRadPerSec,
        hubCenter,
        calibration);
  }

  public static Solution solve(
      Pose3d robotPose,
      Translation2d fieldVelocityMps,
      Translation3d robotAngularVelocityRadPerSec,
      Translation3d hubCenter,
      Calibration calibration) {
    return solve(
        robotPose,
        fieldVelocityMps,
        robotAngularVelocityRadPerSec,
        0.0,
        hubCenter,
        calibration);
  }

  public static Solution solve(
      Pose3d robotPose,
      Translation2d fieldVelocityMps,
      Translation3d robotAngularVelocityRadPerSec,
      double turretYawRateRadPerSec,
      Translation3d hubCenter,
      Calibration calibration) {
    if (robotPose == null || fieldVelocityMps == null ||
        robotAngularVelocityRadPerSec == null ||
        hubCenter == null || calibration == null ||
        !(calibration.mpsScale() > 0.0) ||
        !Double.isFinite(turretYawRateRadPerSec)) {
      return invalid(Double.NaN, Double.NaN);
    }

    Translation3d offsetField =
        LAUNCHER_OFFSET.rotateBy(robotPose.getRotation());
    Translation3d pivotField =
        TURRET_PIVOT.rotateBy(robotPose.getRotation());
    Translation3d muzzleFromPivotField =
        offsetField.minus(pivotField);
    Translation3d launcherPosition =
        robotPose.getTranslation().plus(offsetField);
    Translation3d omegaChassisField =
        robotAngularVelocityRadPerSec.rotateBy(
            robotPose.getRotation());
    Translation3d omegaTurretRobot =
        new Translation3d(0.0, 0.0, turretYawRateRadPerSec);
    Translation3d omegaTurretField =
        omegaTurretRobot.rotateBy(robotPose.getRotation());
    double turretCouple = BALL_DWELL_TIME > 0.0 ? 1.0 : 0.0;
    Translation3d launcherVelocity =
        new Translation3d(
                fieldVelocityMps.getX(),
                fieldVelocityMps.getY(),
                0.0)
            .plus(cross(omegaChassisField, offsetField))
            .plus(cross(omegaTurretField, muzzleFromPivotField)
                      .times(turretCouple));

    double targetX = hubCenter.getX() - launcherPosition.getX();
    double targetY = hubCenter.getY() - launcherPosition.getY();
    double distance = Math.hypot(targetX, targetY);
    if (!(distance > 1e-9) ||
        distance < MIN_DISTANCE_M || distance > MAX_DISTANCE_M) {
      return invalid(Double.NaN, Double.NaN);
    }

    double radialX = targetX / distance;
    double radialY = targetY / distance;
    double tangentX = -radialY;
    double tangentY = radialX;
    double radialVelocity =
        launcherVelocity.getX() * radialX +
        launcherVelocity.getY() * radialY;
    double tangentialVelocity =
        launcherVelocity.getX() * tangentX +
        launcherVelocity.getY() * tangentY;

    double baseAngle = hoodAngleRad(distance);
    double baseSpeed = exitSpeedMps(distance);
    double tof = timeOfFlightS(distance);
    if (!Double.isFinite(baseAngle) || !Double.isFinite(baseSpeed)) {
      return invalid(radialVelocity, tangentialVelocity);
    }

    double radialExit = baseSpeed * Math.cos(baseAngle);
    double verticalExit =
        baseSpeed * Math.sin(baseAngle) - launcherVelocity.getZ();
    Translation3d relativeWorld = new Translation3d(
        radialExit * radialX - tangentialVelocity * tangentX,
        radialExit * radialY - tangentialVelocity * tangentY,
        verticalExit);
    Translation3d relativeRobot =
        relativeWorld.rotateBy(robotPose.getRotation().unaryMinus());

    double horizontalSpeed =
        Math.hypot(relativeRobot.getX(), relativeRobot.getY());
    double exitSpeed = Math.hypot(horizontalSpeed, relativeRobot.getZ());
    double turretYaw =
        Math.atan2(relativeRobot.getY(), relativeRobot.getX());
    double hood =
        Math.atan2(relativeRobot.getZ(), horizontalSpeed) +
        calibration.hoodBiasRad();
    double rps = exitSpeed /
        (2.0 * Math.PI * EFF_RADIUS * calibration.mpsScale());
    double maxRps = EXIT_SPEED_MAX / (2.0 * Math.PI * EFF_RADIUS);

    boolean valid = Double.isFinite(rps) &&
        rps >= 0.0 && rps <= maxRps &&
        hood >= HOOD_MIN && hood <= HOOD_MAX &&
        turretYaw >= TURRET_MIN && turretYaw <= TURRET_MAX &&
        exitSpeed >= EXIT_SPEED_MIN &&
        exitSpeed <= EXIT_SPEED_MAX;
    if (!valid) {
      return invalid(radialVelocity, tangentialVelocity);
    }

    return new Solution(
        true,
        turretYaw,
        hood,
        rps,
        tof,
        exitSpeed,
        radialVelocity,
        tangentialVelocity,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0);
  }

  private static Translation3d cross(
      Translation3d first, Translation3d second) {
    return new Translation3d(
        first.getY() * second.getZ() - first.getZ() * second.getY(),
        first.getZ() * second.getX() - first.getX() * second.getZ(),
        first.getX() * second.getY() - first.getY() * second.getX());
  }

  private static Solution invalid(double radial, double tangential) {
    return new Solution(
        false,
        Double.NaN,
        Double.NaN,
        Double.NaN,
        Double.NaN,
        Double.NaN,
        radial,
        tangential,
        0.0,
        0.0,
        0.0,
        0.0,
        0.0);
  }
}